version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ppe_attendance_backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/backend/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ppe_attendance_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

