import { useEffect, useState } from 'react'

const modules=[
 {label:'INGEST ENGINE',badge:'NVMM ZERO-COPY',title:'Multi-Stream Parallel Video Decoder',desc:'Decode independent camera feeds on the edge without copying frames through host memory.',code:['# Parallel hardware decode and zero-copy delivery','pipeline = Gst.parse_launch(','  "rtspsrc location=feed latency=0 !",','  "rtph265depay ! nvv4l2decoder !",','  "nvvidconv ! video/x-raw(memory:NVMM)"',')','pipeline.set_state(Gst.State.PLAYING)'],stats:[['THREADS','16 Dedicated',''],['FRAME JITTER','< 1.2ms','teal'],['AUTO RECONNECT','Sub-200ms','']]},
 {label:'INFERENCE CO-PROCESSOR',badge:'TENSORRT 8.6 EXECUTOR',title:'YOLOv8-IND-X Optimized Weights',desc:'Serialize the calibrated detector once and execute batched inference with deterministic FP16 kernels.',code:['# Build the edge inference engine','engine = builder.build_serialized_network(','  calibrated_model, fp16_config',' )','with runtime.deserialize_cuda_engine(engine) as plan:','  context = plan.create_execution_context()','  context.execute_async_v3(stream.handle)'],stats:[['BATCH SIZE','8 Streams Sync',''],['PRECISION','FP16 Half-Float','blue'],['VRAM USAGE','3.8 GB / Node','']]},
 {label:'SECONDARY CLASSIFIER',badge:'IOU & POSE ANCHORING',title:'PPE & Ergonomics Verification',desc:'Verify head and body PPE against pose landmarks, zone rules, and worker track identity.',code:['def head_roi(person, landmarks):','  # Select shoulder and nose anchor points','  nose = landmarks["nose"]','  shoulders = landmarks["left_shoulder"], landmarks["right_shoulder"]','  width = abs(shoulders[0].x - shoulders[1].x)','  return crop(person, nose, width * 1.8)'],stats:[['ACCURACY','99.1% Verified','green'],['OCCLUSION TOL','Up to 45% Mask',''],['LANDMARKS','17 Anatomical','']]},
 {label:'ENVIRONMENTAL SENSING',badge:'OPTICAL WAVELET + THERMAL',title:'Dynamic Smoke & Fire Classification',desc:'Combine temporal flicker signatures with radiometric thermal delta to distinguish flame, steam, and dust.',code:['# Reject steam using temporal luminance','flow = optical_flow(previous, current)','flicker = wavelet_energy(flow, bands=3)','thermal_delta = thermal.max_temp - baseline','is_flame = flicker > threshold and thermal_delta > 42','if is_flame: emit("FIRE_SIGNATURE")'],stats:[['FLAME LATENCY','< 150ms Trigger','red'],['STEAM REJECTION','99.7% Discriminant',''],['THERMAL LINK','Radiometric Sync','']]},
 {label:'DISPATCH BUS',badge:'DISTRIBUTED MQTT BROKER',title:'Sub-Second Escalation Matrix',desc:'Route validated events to local relay controls and operator channels with durable QoS delivery.',code:['payload = {"zone": zone_id, "event": event}','client.publish(','  topic=f"safety/{zone_id}/critical",','  payload=json.dumps(payload),','  qos=2, retain=False',' )','await relay.confirm(timeout_ms=250)'],stats:[['DELIVERY GUARANTEE','QoS 2 Exactly-Once','teal'],['FANOUT','>50,000 sub/sec',''],['FAILOVER','Dual Node Raft','']]},
 {label:'PERSISTENCE & UI',badge:'TIMESCALEDB + MINIO',title:'Cryptographic Storage & HUD',desc:'Persist immutable incident evidence and stream signed event updates to the control-room interface.',code:['INSERT INTO incident_events','  (event_id, observed_at, zone, payload_hash)','VALUES ($1, $2, $3, $4);','-- Snapshot object stored in MinIO','-- SHA-256 signature attached to audit event'],stats:[['RETENTION','10-Year Cold S3',''],['ENCRYPTION','AES-256 GCM','blue'],['UI RENDER','WebGL 60 FPS','']]}
]
function Highlight({line}){if(line.trimStart().startsWith('#')||line.trimStart().startsWith('--'))return <span className="code-comment">{line}</span>;const parts=line.split(/("[^"]*"|'[^']*'|\b(?:def|return|with|as|if|await|True|False|INSERT|INTO|VALUES|AND)\b|\b\d+(?:\.\d+)?\b)/g);return <>{parts.map((part,i)=>{let cls='';if(/^(["']).*\1$/.test(part))cls='code-string';else if(/^(def|return|with|as|if|await|True|False|INSERT|INTO|VALUES|AND)$/.test(part))cls='code-keyword';else if(/^\d/.test(part))cls='code-number';return <span className={cls} key={i}>{part}</span>})}</>}
export default function Subsystems(){const [isMobile,setIsMobile]=useState(()=>window.matchMedia('(max-width: 767px)').matches);useEffect(()=>{const media=window.matchMedia('(max-width: 767px)');const update=()=>setIsMobile(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);return <section className="how-subsystems"><header className="how-deep-heading"><div><p>DEEP SUBSYSTEM ANALYSIS</p><h2>Technical Specifications &amp; Implementation</h2></div></header><div className="how-subsystem-grid">{modules.map(item=><article className="how-subsystem how-glass" key={item.title}><header><span>{item.label}</span><b>{item.badge}</b></header><h3>{item.title}</h3><p>{item.desc}</p><details className="how-code-disclosure" open={!isMobile}><summary aria-label={`Show or hide code: ${item.title}`}>Show Code / Implementation</summary><pre><code>{item.code.map((line,i)=><span className="code-line" key={i}><Highlight line={line}/></span>)}</code></pre></details><div className="how-mini-stats">{item.stats.map(([name,value,tone])=><div key={name}><span>{name}</span><b className={tone}>{value}</b></div>)}</div></article>)}</div></section>}
