export default function StatCards() {
  return (
    <section className="monitor-stats" aria-label="Live safety metrics">
      <article className="monitor-stat glass-surface"><div className="monitor-stat__top"><span>COMPLIANCE INDEX</span><span className="stat-symbol stat-symbol--green">↗</span></div><strong className="stat-value">98.4%</strong><div className="stat-status"><span className="mini-pill mini-pill--green">COMPLIANT</span><span className="mono-data">TARGET: &gt;97.5%</span></div><div className="sparkline" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><span className="stat-trend">+0.8% 24h</span></article>
      <article className="monitor-stat glass-surface"><div className="monitor-stat__top"><span>ACTIVE ALERTS</span><span className="stat-symbol stat-symbol--red">!</span></div><strong className="stat-value stat-value--red">3</strong><div className="stat-status"><span className="mini-pill mini-pill--red">PENDING</span><span className="mono-data"><b className="red-text">1 CRIT</b> · <b className="amber-text">2 WARN</b></span></div></article>
      <article className="monitor-stat glass-surface"><div className="monitor-stat__top"><span>INCIDENTS (TODAY)</span><span className="stat-symbol stat-symbol--blue">⌁</span></div><strong className="stat-value">14</strong><div className="stat-status"><span className="mini-pill">LOGGED</span><span className="mono-data"><b className="green-text">11 RESOLVED</b> · <b className="red-text">3 OPEN</b></span></div></article>
      <article className="monitor-stat glass-surface"><div className="monitor-stat__top"><span>INFERENCE LATENCY</span><span className="stat-symbol stat-symbol--teal">◷</span></div><strong className="stat-value stat-value--teal">18.4 <small>ms</small></strong><div className="stat-status"><span className="mini-pill">TENSOR-RT</span><span className="mono-data">EDGE CLUSTER #04</span></div><span className="stat-bottom mono-data">60.0 FPS</span></article>
      <article className="monitor-stat monitor-stat--deployment glass-surface"><div className="monitor-stat__top"><span>DEPLOYMENT TELEMETRY</span><span className="status-dot status-dot--pulse" /></div><strong className="shift-value">SHIFT B <i>•</i> 06:00 - 14:00</strong><div className="camera-online"><i />24/24 CAMERAS ONLINE</div><div className="deployment-meta"><span>NODE: ARCH-01</span><span>UPTIME 99.98%</span></div></article>
    </section>
  )
}
