const cards = [
  { id: '01', badge: 'OPTIMAL', tone: 'green', title: 'Overall Compliance Score', value: '98.4%', delta: '+2.1%', detail: 'vs. 30-day baseline (96.3%)', progress: 98.4, foot: 'TARGET: 99.0%', tail: 'DELTA: -0.6%' },
  { id: '02', badge: '100% ONLINE', tone: 'teal', title: 'Active Monitored Zones', value: '12 / 12', delta: '', detail: 'SECTORS ARMED', foot: '24 Ultra-HD Edge Sensors Connected', tail: 'CLUSTER UPTIME · 99.98% AVAILABILITY' },
  { id: '03', badge: '2 CRITICAL', tone: 'red', title: 'Alerts Logged Today', value: '14', delta: '', detail: 'INCIDENTS', foot: '2 Crit  ·  7 Warn  ·  5 Clr', tail: 'PEAK INTERVAL · 09:00 - 10:00 (SHIFT B)' },
  { id: '04', badge: 'SUB-50ms SLA', tone: 'teal', title: 'Avg Inference Latency', value: '18.2 ms', delta: '', detail: 'OPTIMIZED  ⚡', foot: 'Edge PyTorch TensorRT Engine', tail: 'TARGET THRESHOLD · <50.0 ms PIPELINE' },
]
export default function KpiSummary({ sector, revision }) {
  const factor = sector === 'GLOBAL' ? 1 : 0.94 + (sector.charCodeAt(0) % 4) * .025
  return <section className="analytics-kpis">{cards.map((card, i) => <article className={`analytics-kpi glass-surface tone-${card.tone}`} key={card.id}><header><span>KPI-METRIC // {card.id}</span><b className={`metric-badge badge-${card.tone}`}>{card.badge}</b></header><h2>{card.title}</h2><div className="kpi-reading"><strong>{i === 0 ? `${(98.4 * factor + revision * .03).toFixed(1)}%` : i === 1 ? `${sector === 'GLOBAL' ? '12 / 12' : `${Math.max(2, Math.round(12 * factor))} / 12`}` : i === 2 ? `${Math.max(5, 14 + revision)}` : `${(18.2 * factor).toFixed(1)} ms`}</strong>{i === 0 && <span>{card.delta} ↑</span>}</div><p>{card.detail}</p>{i === 0 ? <><div className="kpi-progress"><i style={{ width: `${Math.min(99, 98.4 * factor)}%` }}/></div><footer><span>{card.foot}</span><span>{card.tail}</span></footer></> : <><div className="kpi-extra">{card.foot}</div><footer>{i === 2 ? <><em>2 Crit</em><em>7 Warn</em><em>5 Clr</em></> : card.tail}</footer></>}</article>)}</section>
}
