import { useState } from 'react'
const days = [91.2,92.1,92.8,92.4,93.5,94.1,93.8,94.7,95.1,94.8,95.6,96.2,95.9,96.7,96.4,97.1,96.8,97.4,97.2,98,97.5,98.1,97.7,98.4]
const types = [['MISSING HELMET / HARD HAT NON-COMPLIANCE',34,'63 EVENTS','amber'],['MISSING HIGH-VISIBILITY SAFETY VEST',28,'52 EVENTS','amber'],['SMOKE DETECTION & THERMAL RUNAWAY',18,'33 EVENTS','red'],['RESTRICTED ZONE UNAUTHORIZED INGRESS',14,'26 EVENTS','blue'],['CRITICAL FLAME / FIRE SIGNATURE DETECTED',6,'12 EVENTS','darkred']]
const risk = [['ZONE B','Assembly','HIGH RISK',68,'HOT-WORKS ACTIVE','Primary: Thermal / Arc','14 Alerts / Wk','red'],['ZONE C','Chemical','MODERATE',42,'VAPOR DETECTORS ARMED','Primary: Goggles / Respirator','6 Alerts / Wk','amber'],['ZONE A','Heavy Fab','LOW RISK',24,'CRANE PATH SECURE','Primary: Boundary Ingress','3 Alerts / Wk','green'],['ZONE D','Logistics','MINIMAL',12,'AGV PATH CLEAR','Primary: Speed Compliance','1 Alert / Wk','white']]
function ComplianceChart({ sector }) {
 const [point, setPoint] = useState(null)
 const coords = days.map((v,i)=>`${28+i*28},${150-(v-90)*8.4}`).join(' ')
 return <article className="analytics-chart glass-surface"><header className="chart-heading"><div><span className="chart-icon">⌁</span><h2>Compliance Trend (30 Days)</h2></div><span className="chart-small">30D ROLLING WINDOW</span></header><div className="chart-legend"><span><i className="legend-line"/>Site Compliance</span><span><i className="legend-line legend-floor"/>Floor 95.0%</span></div><div className="line-chart-wrap"><svg viewBox="0 0 710 190" role="img" aria-label="Compliance trend line chart" onMouseLeave={()=>setPoint(null)}>{[30,70,110,150].map(y=><line key={y} x1="28" x2="672" y1={y} y2={y} className="chart-grid"/>)}<defs><linearGradient id="complianceFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#54d7c3" stopOpacity=".36"/><stop offset="1" stopColor="#54d7c3" stopOpacity="0"/></linearGradient></defs><line x1="28" x2="672" y1="108" y2="108" className="floor-line"/><polygon points={`28,${150-(days[0]-90)*8.4} ${coords} 672,160 28,160`} fill="url(#complianceFill)"/><polyline points={coords} className="compliance-line"/>{days.map((v,i)=><circle key={i} cx={28+i*28} cy={150-(v-90)*8.4} r="5" className="line-hit" onMouseEnter={()=>setPoint({x:28+i*28,y:150-(v-90)*8.4,value:v,index:i})}/>)}{point&&<g className="chart-tooltip"><rect x={Math.min(point.x-40,595)} y={point.y-38} width="84" height="23" rx="7"/><text x={Math.min(point.x+2,637)} y={point.y-23}>{`DAY ${point.index+1}: ${point.value.toFixed(1)}%`}</text></g>}<text x="570" y="42" className="chart-now">NOW: 98.4%</text></svg></div><footer className="chart-axis"><span>DAY -30 (91.2%)</span><span>DAY -20</span><span>DAY -10</span><span>TODAY (98.4%)</span></footer></article>
}
function IncidentTypeChart(){return <article className="analytics-chart glass-surface"><header className="chart-heading"><div><span className="chart-icon">◔</span><h2>Incidents by Type (30-Day Distribution)</h2></div><span className="chart-small">N = 186 INCIDENTS</span></header><div className="incident-bars">{types.map(([name,pct,count,tone])=><div className="incident-bar-row" key={name}><div><span>{name}</span><small>{count}</small></div><div className="bar-track"><i className={`bar-${tone}`} style={{width:`${pct*2.35}%`}}/></div><b>{pct}%</b></div>)}</div></article>}
function RiskMatrix(){return <article className="analytics-chart glass-surface"><header className="chart-heading"><div><span className="chart-icon">⬡</span><h2>Zone Risk Index Matrix</h2></div><span className="chart-small">COMPOSITE HAZARD SCORE</span></header><div className="risk-matrix">{risk.map(([zone,name,label,score,state,primary,alerts,tone])=><div className={`risk-card risk-${tone}`} key={zone}><header><span>{zone} · {name}</span><b>{label}</b></header><strong>{score}<small> / 100</small></strong><div className="risk-progress"><i style={{width:`${score}%`}}/></div><p>{state}</p><footer><span>{primary}</span><b>{alerts}</b></footer></div>)}</div></article>}
function LatencyChart(){const bars=[16,17,17,16,18,16,18,19,17,18,18,20,21,20,19,18,17,19,18,18,16,17,18,17];return <article className="analytics-chart glass-surface"><header className="chart-heading"><div><span className="chart-icon">▥</span><h2>Detection Latency &amp; GPU Inference Load</h2></div><span className="chart-small"><i className="pulse-green"/> 60 FPS SYNCHRONIZED</span></header><div className="latency-chart"><div className="latency-guide latency-max"><span>MAX SLA: 50.0ms</span></div><div className="latency-guide latency-mid"><span>MEDIAN: 18.2ms</span></div><div className="latency-bars">{bars.map((v,i)=><i key={i} className={i===12||i===13?'peak':''} style={{height:`${v*3.05}px`}} title={`${String(i).padStart(2,'0')}:00 · ${v}.0ms`}/>)}</div><svg viewBox="0 0 720 140" preserveAspectRatio="none"><polyline points={bars.map((v,i)=>`${15+i*30},${126-v*2.3}`).join(' ')} /></svg></div><footer className="chart-axis"><span>00:00 (16.4ms)</span><span>06:00 (17.1ms)</span><span>12:00 PEAK (20.8ms)</span><span>18:00 (18.6ms)</span><span>23:59 (17.8ms)</span></footer></article>}
export default function Charts({sector}){return <section className="analytics-charts" data-sector={sector}><ComplianceChart sector={sector}/><IncidentTypeChart/><RiskMatrix/><LatencyChart/></section>}
