export default function ThreatStream({ threats, onAction, hideResolved, setHideResolved, streamRef, onExport }) {
  const visibleThreats = hideResolved ? threats.filter((item) => item.kind !== 'resolved') : threats
  return (
    <aside className="threat-stream glass-surface" aria-label="Real-time threat and incident stream">
      <header className="threat-stream__header"><div className="stream-title"><span className="stream-emergency-icon">!</span><div><h2>THREAT <span>&amp; INCIDENT STREAM</span></h2><p><i /> SIMULATED EVENT BUS · SAMPLE DATA</p></div></div><div className="stream-header-actions"><span aria-label="Audio alerts enabled">◖))</span><button type="button" aria-label={hideResolved ? 'Show resolved incidents' : 'Hide resolved incidents'} onClick={() => setHideResolved((value) => !value)}>☷</button></div></header>
      <div className="threat-list" ref={streamRef}>{visibleThreats.map((threat) => <article className={`threat-card threat-card--${threat.kind}`} key={threat.id}><div className="threat-card__head"><span className="threat-severity"><i />{threat.kind === 'critical' ? 'CRITICAL' : threat.kind === 'warning' ? 'WARNING' : 'RESOLVED'}</span><span className="threat-id">{threat.id}</span></div><div className="threat-card__title"><h3>{threat.title}</h3><time>{threat.time}</time></div><p className="threat-location">{threat.location}</p><p className="threat-description">{threat.description}</p>{threat.kind !== 'resolved' && <div className="threat-actions">{(threat.actions || (threat.kind === 'critical' ? ['TRIGGER ALARM', 'DISPATCH MARSHAL', 'ACK'] : ['SPEAKER WARNING', 'LOG VIOLATION'])).map((action) => <button type="button" key={action} className={`threat-action${action.includes('ALARM') || action.includes('ISOLATE') ? ' threat-action--red' : action.includes('WARNING') ? ' threat-action--amber' : action.includes('EXHAUST') ? ' threat-action--teal' : ''}`} onClick={() => onAction(action, threat)}>{action}</button>)}</div>}</article>)}</div>
      <footer className="threat-stream__footer"><span><i /> DISPATCH PROTOCOL ACTIVE</span><button type="button" onClick={onExport}>LOG EXPORT (.CSV) <b>↓</b></button></footer>
    </aside>
  )
}
